################################################
# Author: Luis Ramirez                         #
# Created: 11-14-2019                          #
# Updated: 1-23-2026                           #
################################################
<#
.SYNOPSIS
    Staged workflow for cleaning up stale computer objects safely.

.DESCRIPTION
    Three-stage cleanup process for stale computers:
    
    Stage 1 - DISABLE (Days 0-30):
    - Disable computer account
    - Add description with disable date
    - Move to "Disabled Computers" OU
    - Send notification email
    
    Stage 2 - STAGE FOR DELETION (Days 31-60):
    - Move to "TO DELETE" OU
    - Update description
    - Final warning email to IT
    
    Stage 3 - DELETE (Days 61+):
    - Export final backup
    - Delete from AD
    - Log deletion for compliance
    
    Safety Features:
    - Dry-run mode
    - Approval required for delete stage
    - Full backup before each action
    - Rollback capability
    - Email notifications

.PARAMETER CSVFile
    CSV file from Find-StaleADObjects.ps1

.PARAMETER Stage
    Which stage to execute: Disable, StageForDelete, or Delete

.PARAMETER DisabledOU
    OU for disabled computers

.PARAMETER ToDeleteOU
    OU for computers staged for deletion

.PARAMETER DryRun
    Test mode - show actions without executing

.PARAMETER EmailRecipient
    Email address for notifications

.PARAMETER SMTPServer
    SMTP server for email

.EXAMPLE
    .\Remove-StaleComputersWorkflow.ps1 -CSVFile "stale-computers.csv" -Stage Disable -DryRun
    
    Test disabling stale computers.

.EXAMPLE
    .\Remove-StaleComputersWorkflow.ps1 -CSVFile "stale-computers.csv" -Stage Delete -EmailRecipient "it@company.com" -SMTPServer "smtp.company.com"
    
    Delete computers staged for 60+ days with email notification.

.NOTES
    Recommended Schedule:
    - Weekly: Run Find-StaleADObjects.ps1
    - Weekly: Run this script with -Stage Disable
    - Monthly: Run with -Stage StageForDelete
    - Quarterly: Run with -Stage Delete (after management review)

Author: Luis Ramirez
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$CSVFile,

    [Parameter(Mandatory = $true)]
    [ValidateSet("Disable", "StageForDelete", "Delete")]
    [string]$Stage,

    [Parameter(Mandatory = $false)]
    [string]$DisabledOU = "OU=Disabled Computers,OU=Computers,DC=contoso,DC=com",

    [Parameter(Mandatory = $false)]
    [string]$ToDeleteOU = "OU=TO DELETE,OU=Computers,DC=contoso,DC=com",

    [Parameter(Mandatory = $false)]
    [string]$BackupPath = ".\Computer-Cleanup-Backup-$(Get-Date -Format 'yyyyMMdd-HHmmss').csv",

    [Parameter(Mandatory = $false)]
    [string]$EmailRecipient,

    [Parameter(Mandatory = $false)]
    [string]$SMTPServer,

    [Parameter(Mandatory = $false)]
    [switch]$DryRun,

    [Parameter(Mandatory = $false)]
    [switch]$Force
)

#region Import Module

try {
    Import-Module ActiveDirectory -ErrorAction Stop
}
catch {
    Write-Error "ActiveDirectory module required."
    exit 1
}

#endregion

#region Helper Functions

function Write-WorkflowLog {
    param(
        [string]$Message,
        [ValidateSet("Info", "Warning", "Error", "Success")]
        [string]$Level = "Info"
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $color = switch ($Level) {
        "Success" { "Green" }
        "Warning" { "Yellow" }
        "Error" { "Red" }
        default { "White" }
    }
    
    Write-Host "[$timestamp] [$Level] $Message" -ForegroundColor $color
    
    # Also log to file
    "[$timestamp] [$Level] $Message" | Out-File -FilePath $script:LogFile -Append
}

function Send-NotificationEmail {
    param(
        [string]$Subject,
        [string]$Body,
        [int]$AffectedCount
    )
    
    if (-not $EmailRecipient -or -not $SMTPServer) {
        Write-WorkflowLog "Email notification skipped (no recipient or SMTP server configured)" -Level Info
        return
    }
    
    try {
        $emailBody = @"
<html>
<body style="font-family: Arial, sans-serif;">
<h2>$Subject</h2>
$Body
<p><strong>Affected Computers:</strong> $AffectedCount</p>
<p><strong>Stage:</strong> $Stage</p>
<p><strong>Timestamp:</strong> $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')</p>
<hr>
<p style="font-size: 11px; color: #666;">Automated cleanup workflow | Generated by Remove-StaleComputersWorkflow.ps1</p>
</body>
</html>
"@
        
        Send-MailMessage -To $EmailRecipient `
            -From "AD-Automation@company.com" `
            -Subject $Subject `
            -Body $emailBody `
            -BodyAsHtml `
            -SmtpServer $SMTPServer `
            -ErrorAction Stop
        
        Write-WorkflowLog "Email notification sent to $EmailRecipient" -Level Success
    }
    catch {
        Write-WorkflowLog "Failed to send email: $_" -Level Warning
    }
}

#endregion

#region Main Script

$script:LogFile = ".\Computer-Cleanup-$Stage-$(Get-Date -Format 'yyyyMMdd-HHmmss').log"

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Stale Computer Cleanup Workflow" -ForegroundColor Cyan
Write-Host "Stage: $Stage" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

if ($DryRun) {
    Write-WorkflowLog "⚠️  DRY-RUN MODE - No changes will be made" -Level Warning
}

# Load CSV
Write-WorkflowLog "Loading CSV file: $CSVFile" -Level Info
if (-not (Test-Path $CSVFile)) {
    Write-WorkflowLog "CSV file not found: $CSVFile" -Level Error
    exit 1
}

$computers = Import-Csv $CSVFile | Where-Object { $_.Type -eq "Computer" }
Write-WorkflowLog "Loaded $($computers.Count) computer objects from CSV" -Level Info

if ($computers.Count -eq 0) {
    Write-WorkflowLog "No computers to process" -Level Info
    exit 0
}

# Create backup
Write-WorkflowLog "Creating backup: $BackupPath" -Level Info
$backupData = @()

$processedCount = 0
$errorCount = 0

#region Stage-Specific Processing

switch ($Stage) {
    "Disable" {
        Write-WorkflowLog "`nStage 1: DISABLING computers" -Level Warning
        
        foreach ($comp in $computers) {
            try {
                $computer = Get-ADComputer -Identity $comp.Name -Properties Description, Enabled -ErrorAction Stop
                
                # Backup current state
                $backupData += [PSCustomObject]@{
                    Name = $computer.Name
                    DistinguishedName = $computer.DistinguishedName
                    PreviousDescription = $computer.Description
                    PreviousEnabled = $computer.Enabled
                    ActionDate = Get-Date
                    Stage = "Disabled"
                }
                
                if ($computer.Enabled -eq $false) {
                    Write-WorkflowLog "  SKIP: $($computer.Name) - Already disabled" -Level Info
                    continue
                }
                
                if ($DryRun) {
                    Write-WorkflowLog "  WOULD DISABLE: $($computer.Name)" -Level Warning
                }
                else {
                    # Disable account
                    Disable-ADAccount -Identity $computer.Name -ErrorAction Stop
                    
                    # Update description
                    $newDescription = "DISABLED $(Get-Date -Format 'yyyy-MM-dd') - Stale object (inactive $($comp.DaysSinceLogon) days)"
                    Set-ADComputer -Identity $computer.Name -Description $newDescription -ErrorAction Stop
                    
                    # Move to Disabled OU
                    Move-ADObject -Identity $computer.DistinguishedName -TargetPath $DisabledOU -ErrorAction Stop
                    
                    Write-WorkflowLog "  ✓ DISABLED: $($computer.Name)" -Level Success
                    $processedCount++
                }
            }
            catch {
                Write-WorkflowLog "  ERROR: $($comp.Name) - $_" -Level Error
                $errorCount++
            }
        }
        
        $emailBody = @"
<p>The following computers have been <strong>disabled</strong> due to inactivity:</p>
<p>These computers will remain disabled for 30 days before moving to deletion staging.</p>
<p>If any of these computers should remain active, please re-enable them immediately.</p>
"@
        Send-NotificationEmail -Subject "AD Cleanup: Computers Disabled (Stage 1)" -Body $emailBody -AffectedCount $processedCount
    }
    
    "StageForDelete" {
        Write-WorkflowLog "`nStage 2: STAGING for deletion (disabled 30+ days)" -Level Warning
        
        $cutoffDate = (Get-Date).AddDays(-30)
        
        foreach ($comp in $computers) {
            try {
                $computer = Get-ADComputer -Identity $comp.Name -Properties Description, Enabled, whenChanged -ErrorAction Stop
                
                # Only process computers that have been disabled for 30+ days
                if ($computer.Enabled -eq $true) {
                    Write-WorkflowLog "  SKIP: $($computer.Name) - Still enabled" -Level Info
                    continue
                }
                
                if ($computer.whenChanged -gt $cutoffDate) {
                    Write-WorkflowLog "  SKIP: $($computer.Name) - Disabled less than 30 days ago" -Level Info
                    continue
                }
                
                # Backup current state
                $backupData += [PSCustomObject]@{
                    Name = $computer.Name
                    DistinguishedName = $computer.DistinguishedName
                    PreviousDescription = $computer.Description
                    ActionDate = Get-Date
                    Stage = "StagedForDeletion"
                }
                
                if ($DryRun) {
                    Write-WorkflowLog "  WOULD STAGE: $($computer.Name)" -Level Warning
                }
                else {
                    # Update description
                    $newDescription = "TO DELETE $(Get-Date -Format 'yyyy-MM-dd') - Disabled for 30+ days"
                    Set-ADComputer -Identity $computer.Name -Description $newDescription -ErrorAction Stop
                    
                    # Move to TO DELETE OU
                    Move-ADObject -Identity $computer.DistinguishedName -TargetPath $ToDeleteOU -ErrorAction Stop
                    
                    Write-WorkflowLog "  ✓ STAGED: $($computer.Name)" -Level Warning
                    $processedCount++
                }
            }
            catch {
                Write-WorkflowLog "  ERROR: $($comp.Name) - $_" -Level Error
                $errorCount++
            }
        }
        
        $emailBody = @"
<p>The following computers have been <strong>moved to TO DELETE OU</strong> after being disabled for 30+ days:</p>
<p>These computers will be <strong>permanently deleted in 30 days</strong> unless re-enabled.</p>
<p><strong style="color: red;">FINAL WARNING: Review this list carefully!</strong></p>
"@
        Send-NotificationEmail -Subject "AD Cleanup: Computers Staged for Deletion (Stage 2)" -Body $emailBody -AffectedCount $processedCount
    }
    
    "Delete" {
        Write-WorkflowLog "`nStage 3: DELETING computers (staged 30+ days)" -Level Error
        
        if (-not $Force) {
            Write-Host "`n⚠️  WARNING: You are about to PERMANENTLY DELETE computer objects!" -ForegroundColor Red
            Write-Host "This action CANNOT be undone!`n" -ForegroundColor Red
            $confirmation = Read-Host "Type 'DELETE' to confirm"
            
            if ($confirmation -ne "DELETE") {
                Write-WorkflowLog "Deletion cancelled by user" -Level Info
                exit 0
            }
        }
        
        $cutoffDate = (Get-Date).AddDays(-30)
        
        foreach ($comp in $computers) {
            try {
                $computer = Get-ADComputer -Identity $comp.Name -Properties Description, whenChanged -ErrorAction Stop
                
                # Only delete computers in TO DELETE OU for 30+ days
                if ($computer.DistinguishedName -notlike "*$ToDeleteOU*") {
                    Write-WorkflowLog "  SKIP: $($computer.Name) - Not in TO DELETE OU" -Level Info
                    continue
                }
                
                if ($computer.whenChanged -gt $cutoffDate) {
                    Write-WorkflowLog "  SKIP: $($computer.Name) - Staged less than 30 days ago" -Level Info
                    continue
                }
                
                # Full backup before deletion
                $backupData += [PSCustomObject]@{
                    Name = $computer.Name
                    DistinguishedName = $computer.DistinguishedName
                    Description = $computer.Description
                    WhenChanged = $computer.whenChanged
                    ActionDate = Get-Date
                    Stage = "Deleted"
                }
                
                if ($DryRun) {
                    Write-WorkflowLog "  WOULD DELETE: $($computer.Name)" -Level Error
                }
                else {
                    Remove-ADComputer -Identity $computer.Name -Confirm:$false -ErrorAction Stop
                    Write-WorkflowLog "  ✓ DELETED: $($computer.Name)" -Level Error
                    $processedCount++
                }
            }
            catch {
                Write-WorkflowLog "  ERROR: $($comp.Name) - $_" -Level Error
                $errorCount++
            }
        }
        
        $emailBody = @"
<p>The following computers have been <strong style="color: red;">PERMANENTLY DELETED</strong> from Active Directory:</p>
<p>These objects were disabled for 60+ days and staged for deletion for 30+ days.</p>
<p>A full backup has been saved to: $BackupPath</p>
"@
        Send-NotificationEmail -Subject "AD Cleanup: Computers DELETED (Stage 3)" -Body $emailBody -AffectedCount $processedCount
    }
}

#endregion

#region Save Backup

if ($backupData.Count -gt 0) {
    $backupData | Export-Csv -Path $BackupPath -NoTypeInformation
    Write-WorkflowLog "Backup saved: $BackupPath ($($backupData.Count) objects)" -Level Success
}

#endregion

#region Summary

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "Workflow Complete" -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

Write-WorkflowLog "Processed: $processedCount" -Level Success
Write-WorkflowLog "Errors: $errorCount" -Level $(if ($errorCount -gt 0) { "Warning" } else { "Info" })
Write-WorkflowLog "Log file: $script:LogFile" -Level Info

if ($Stage -eq "Disable") {
    Write-Host "`nNext Steps:" -ForegroundColor Yellow
    Write-Host "  1. Review disabled computers in 30 days" -ForegroundColor White
    Write-Host "  2. Run: .\Remove-StaleComputersWorkflow.ps1 -CSVFile '$CSVFile' -Stage StageForDelete" -ForegroundColor White
}
elseif ($Stage -eq "StageForDelete") {
    Write-Host "`nNext Steps:" -ForegroundColor Yellow
    Write-Host "  1. Review staged computers in 30 days" -ForegroundColor White
    Write-Host "  2. Get final approval from management" -ForegroundColor White
    Write-Host "  3. Run: .\Remove-StaleComputersWorkflow.ps1 -CSVFile '$CSVFile' -Stage Delete" -ForegroundColor White
}
else {
    Write-Host "`n✓ Cleanup complete - computers permanently deleted" -ForegroundColor Green
    Write-Host "  Backup saved: $BackupPath`n" -ForegroundColor Green
}

#endregion
